common:
  grpcAddress: ":1234"
  httpAddress: ":12345"
  serviceName: "micro_service"

redis:
  address: "127.0.0.1:6379"
  maxPoolSize: 200 # 线程池大小
  db: 0 # 选择redis的数据库

mysql:
  address: "root:123456@tcp(127.0.0.1:3306)/test?charset=utf8&parseTime=True&loc=Local"
  maxIdleConn: [10]
  maxOpenConn: [10]
  MaxLifetime: [60]

rpcServer:
  backend1:
    name: "backend1"
    address: "backend1:10001"